### ISSUE TITLE
Review sections one by one

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#31]
- [ ] Abstract (**Issues**: #15, #25. **PR**: #29)
- [ ] Status of This Document (**Issues**: #15. **PR**: …)
- [ ] 1. Introduction (**Issues**: #15. **PR**: …)
- [ ] 2. Definitions (**Issues**: #15. **PR**: …)
    - [ ] 2.1    People & Data (**Issues**: #15, #26. **PR**: #30)
    - [ ] 2.2    The Parties (**Issues**: #15. **PR**: …)
    - [ ] 2.3    Acting on Data (**Issues**: #15. **PR**: …)
    - [ ] 2.4    Contexts and Privacy (**Issues**: #15. **PR**: …)
    - [ ] 2.5    User Agents (**Issues**: #15. **PR**: …)
    - [ ] 2.6    Identity on the Web (**Issues**: #15. **PR**: #28)
    - [ ] 2.7    User Control and Autonomy (**Issues**: #15. **PR**: …)
    - [ ] 2.8    Opt-in, Consent, Opt-out, Global Controls (**Issues**: #15. **PR**: …)
    - [ ] 2.9    Collective Issues in Privacy (**Issues**: #15. **PR**: …)
- [ ] 3. Privacy principles by category (**Issues**: #15. **PR**: …)
    - [ ] 3.1    Unwanted same-site recognition (**Issues**: #15. **PR**: …)
    - [ ] 3.2    Unwanted cross-site recognition (**Issues**: #15. **PR**: …)
    - [ ] 3.3    Sensitive information disclosure (**Issues**: #15. **PR**: …)
    - [ ] 3.4    Intrusive behavior (**Issues**: #15. **PR**: …)
    - [ ] 3.5    Powerful capabilities (**Issues**: #15. **PR**: …)

**Comment by darobin** [comment]
This isn't the right structure for review any more.
